using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Globalization;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Markup;
using System.Windows.Threading;
using System.Windows.Interop;
using System.Runtime.InteropServices;
using Forms=System.Windows.Forms;

namespace Playtime {
 public class DesktopLink {public string Path {get;set;} public string Label {get;set;}}
 public static class U {
  public static Brush Color(string s){return (Brush)new BrushConverter().ConvertFromString(s);}
  public static TextBlock Text(string text,double size=14,string color="#1D1D1F",bool bold=false){return new TextBlock{Text=text,FontSize=size,Foreground=Color(color),FontWeight=bold?FontWeights.SemiBold:FontWeights.Normal,VerticalAlignment=VerticalAlignment.Center,TextWrapping=TextWrapping.Wrap};}
  public static Button Button(string text,Action action,bool filled=false){var b=new Button{Content=text,Padding=new Thickness(14,9,14,9),Margin=new Thickness(0,0,6,0),Background=Color(filled?"#007AFF":"Transparent"),Foreground=Color(filled?"White":"#007AFF"),Cursor=System.Windows.Input.Cursors.Hand};b.Click+=(o,e)=>action();return b;}
  public static Border Card(UIElement child,Thickness? padding=null){return new Border{Background=Brushes.White,CornerRadius=new CornerRadius(20),Padding=padding??new Thickness(24),Margin=new Thickness(0,0,0,12),Child=child};}
  public static StackPanel Row(params UIElement[] children){var s=new StackPanel{Orientation=Orientation.Horizontal};foreach(var c in children)s.Children.Add(c);return s;}
  public static TextBox Field(StackPanel host,string caption,string value){host.Children.Add(Text(L.T(caption),13,"#6E6E73"));var b=new TextBox{Text=value??"",Margin=new Thickness(0,7,0,16),Padding=new Thickness(10),MinHeight=37};host.Children.Add(b);return b;}
  public static Window Dialog(Window owner,string title,double width=580){var w=new Window{Owner=owner,Title=title,Width=width,SizeToContent=SizeToContent.Height,MaxHeight=800,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=Color("#F5F5F7"),FontFamily=new FontFamily("Segoe UI, Microsoft YaHei UI, Yu Gothic UI"),FontSize=14,ShowInTaskbar=false};w.Resources=Styles();return w;}
  public static ResourceDictionary Styles(){return (ResourceDictionary)XamlReader.Parse(@"<ResourceDictionary xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
<Style TargetType='Button'><Setter Property='BorderThickness' Value='0'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Button'><Border x:Name='b' Background='{TemplateBinding Background}' Padding='{TemplateBinding Padding}' CornerRadius='9'><ContentPresenter HorizontalAlignment='Center' VerticalAlignment='Center'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='b' Property='Opacity' Value='0.72'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='b' Property='BorderThickness' Value='2'/><Setter TargetName='b' Property='BorderBrush' Value='#87B9FF'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter TargetName='b' Property='Opacity' Value='0.35'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='TextBox'><Setter Property='BorderBrush' Value='#D7D7DC'/><Setter Property='Background' Value='White'/><Setter Property='BorderThickness' Value='1'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='TextBox'><Border BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}' Background='{TemplateBinding Background}' CornerRadius='8'><ScrollViewer x:Name='PART_ContentHost' Margin='{TemplateBinding Padding}'/></Border><ControlTemplate.Triggers><Trigger Property='IsKeyboardFocused' Value='True'><Setter Property='BorderBrush' Value='#007AFF'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style></ResourceDictionary>");}
  public static void Safe(Window owner,Action action){try{action();}catch(Exception ex){MessageBox.Show(owner,L.T("error")+"\n"+ex.Message,L.T("title"),MessageBoxButton.OK,MessageBoxImage.Warning);}}
 }
 public class Dashboard : Window {
  readonly App app;readonly DispatcherTimer timer;int page;Grid body;ScrollViewer scroll;string fingerprint;bool first=true;
  public Dashboard(App app){this.app=app;Title=L.T("title");Width=1020;Height=760;MinWidth=830;MinHeight=620;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=U.Color("#F5F5F7");FontFamily=new FontFamily("Segoe UI, Microsoft YaHei UI, Yu Gothic UI");FontSize=14;Resources=U.Styles();AllowDrop=true;
   Drop+=(o,e)=>{if(e.Data.GetDataPresent(DataFormats.FileDrop)){var files=(string[])e.Data.GetData(DataFormats.FileDrop);foreach(var f in files)U.Safe(this,()=>EditGame(null,f));}};
   timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};timer.Tick+=(o,e)=>Refresh();Loaded+=(o,e)=>{Render();timer.Start();if(first&&!app.Store.Config.onboardingComplete){first=false;Welcome();}};Closed+=(o,e)=>timer.Stop();
  }
  void Refresh(){var list=app.Tracker.Snapshot();string key=string.Join("|",list.Select(s=>s.id+s.status+s.durationSeconds.ToString("R")))+app.Tracker.Paused+app.Tracker.Error;if(key!=fingerprint&&page!=2){fingerprint=key;Render();}}
  public void Render(){double offset=scroll==null?0:scroll.VerticalOffset;Title=L.T("title");
   var root=new Grid{Margin=new Thickness(32,26,32,18)};root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});Content=root;
   var header=new Grid{Margin=new Thickness(0,0,0,25)};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});header.Children.Add(U.Text(L.T("title"),30,"#1D1D1F",true));
   var nav=new StackPanel{Orientation=Orientation.Horizontal};string[] tabs={"overview","history","settings"};for(int i=0;i<3;i++){int p=i;var b=U.Button(L.T(tabs[i]),()=>{page=p;scroll=null;Render();});b.Foreground=U.Color(page==i?"#1D1D1F":"#6E6E73");b.Background=page==i?Brushes.White:Brushes.Transparent;b.Margin=new Thickness(0);nav.Children.Add(b);}var segmented=new Border{Background=U.Color("#EAEAED"),CornerRadius=new CornerRadius(12),Padding=new Thickness(4),Child=nav,VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(segmented,1);header.Children.Add(segmented);root.Children.Add(header);
   body=new Grid();Grid.SetRow(body,1);root.Children.Add(body);scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};body.Children.Add(scroll);var content=new StackPanel{Margin=new Thickness(0,0,5,0)};scroll.Content=content;
   if(page==2)Settings(content);else {var sessions=app.Tracker.Snapshot();if(page==0)Overview(content,sessions);else History(content,sessions);}
   var footer=new Grid{Margin=new Thickness(0,12,0,0)};var status=U.Button("● "+L.T(app.Tracker.Paused?"paused":"tracking"),()=>{app.Tracker.SetPaused(!app.Tracker.Paused);app.RefreshTray();Render();});status.HorizontalAlignment=HorizontalAlignment.Left;status.Foreground=U.Color(app.Tracker.Paused?"#B7791F":"#28824B");status.FontSize=12;footer.Children.Add(status);var help=U.Button(L.T("help")+" ↗",()=>Help());help.HorizontalAlignment=HorizontalAlignment.Right;help.FontSize=12;footer.Children.Add(help);Grid.SetRow(footer,2);root.Children.Add(footer);scroll.ScrollToVerticalOffset(offset);
  }
  void Overview(StackPanel host,List<Session> sessions){
   double total=sessions.Sum(s=>s.durationSeconds);var hero=new Grid();foreach(int i in new[]{0,1,2})hero.ColumnDefinitions.Add(new ColumnDefinition());
   var metric=new StackPanel();metric.Children.Add(U.Text(L.T("total"),13,"#86868B"));metric.Children.Add(U.Row(U.Text((total>=3600?total/3600:total/60).ToString("0.#"),43,"#007AFF",true),new TextBlock{Text=" "+L.T(total>=3600?"hours":"minutes"),Margin=new Thickness(8,23,0,0),Foreground=U.Color("#86868B")}));hero.Children.Add(metric);
   int count=sessions.Where(s=>s.status!="manual"&&s.status!="failed").Select(s=>s.runKey??s.id).Distinct().Count();
   for(int i=1;i<3;i++){var panel=new StackPanel{Margin=new Thickness(22,0,0,0),VerticalAlignment=VerticalAlignment.Center};panel.Children.Add(U.Text(L.T(i==1?"runs":"games"),13,"#86868B"));panel.Children.Add(U.Text((i==1?count:app.Store.Config.games.Count).ToString(),29,"#1D1D1F",true));Grid.SetColumn(panel,i);hero.Children.Add(panel);}host.Children.Add(U.Card(hero,new Thickness(26)));
   var heading=new DockPanel{Margin=new Thickness(0,9,0,13)};var add=U.Button("+ "+L.T("add"),()=>EditGame(null,null),true);DockPanel.SetDock(add,Dock.Right);heading.Children.Add(add);heading.Children.Add(U.Text(L.T("mygames"),20,"#1D1D1F",true));host.Children.Add(heading);
   if(app.Store.Warning!=null)host.Children.Add(U.Text(L.T(app.Store.Warning),13,"#B06B20"));if(app.Tracker.Error!=null)host.Children.Add(U.Text(L.T(app.Tracker.Error),13,"#B06B20"));
   if(app.Store.Config.games.Count==0){var empty=new StackPanel{Margin=new Thickness(8,24,8,24)};empty.Children.Add(U.Text(L.T("empty"),20,"#1D1D1F",true));empty.Children.Add(U.Text(L.T("drop"),14,"#86868B"));host.Children.Add(U.Card(empty));}
   foreach(var g in app.Store.Config.games.ToArray()){
    var entries=sessions.Where(s=>s.gameId==g.id).ToList();var grid=new Grid();grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(60)});grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});
    var icon=new Border{Width=46,Height=46,CornerRadius=new CornerRadius(12),Background=U.Color("#EDF4FF"),VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Left};icon.Child=IconFor(g);grid.Children.Add(icon);
    var names=new StackPanel{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,15,0)};names.Children.Add(U.Text(g.name,18,"#1D1D1F",true));string last=entries.OrderByDescending(s=>s.startTime).Select(s=>s.startTime).FirstOrDefault();names.Children.Add(U.Text(last==null?L.T("never"):L.T("recent")+"  "+L.Date(last),12,"#86868B"));Grid.SetColumn(names,1);grid.Children.Add(names);
    var right=new StackPanel{VerticalAlignment=VerticalAlignment.Center};right.Children.Add(U.Text(L.Duration(entries.Sum(s=>s.durationSeconds)),19,"#1D1D1F",true));if(entries.Any(s=>s.status=="running"))right.Children.Add(U.Text(L.T("running"),12,"#28824B"));if(!g.enabled)right.Children.Add(U.Text(L.T("paused"),12,"#B7791F"));Grid.SetColumn(right,2);grid.Children.Add(right);
    var more=U.Button("···",()=>{});more.FontSize=22;more.Margin=new Thickness(13,0,0,0);more.Padding=new Thickness(6);more.VerticalAlignment=VerticalAlignment.Center;var menu=new ContextMenu();AddMenu(menu,"start",()=>Launch(g));AddMenu(menu,"edit",()=>EditGame(g,null));AddMenu(menu,"manual",()=>Manual(g));AddMenu(menu,"remove",()=>{if(MessageBox.Show(this,L.T("removeConfirm"),L.T("title"),MessageBoxButton.OKCancel)==MessageBoxResult.OK){lock(app.Store.Gate)app.Store.Config.games.Remove(g);app.Store.SaveConfig();app.Tracker.Changed();Render();}});more.ContextMenu=menu;more.Click+=(o,e)=>{menu.PlacementTarget=more;menu.IsOpen=true;};Grid.SetColumn(more,3);grid.Children.Add(more);host.Children.Add(U.Card(grid));
   }
  }
  readonly Dictionary<string,ImageSource> icons=new Dictionary<string,ImageSource>();
  UIElement IconFor(Game g){ImageSource source=null;if(!icons.TryGetValue(g.executable??"",out source)){try{using(var icon=System.Drawing.Icon.ExtractAssociatedIcon(g.executable)){source=Imaging.CreateBitmapSourceFromHIcon(icon.Handle,Int32Rect.Empty,System.Windows.Media.Imaging.BitmapSizeOptions.FromEmptyOptions());source.Freeze();}}catch{}icons[g.executable??""]=source;}if(source!=null)return new Image{Source=source,Width=32,Height=32};var text=U.Text(new string(g.name.Take(2).ToArray()).ToUpperInvariant(),16,"#007AFF",true);text.HorizontalAlignment=HorizontalAlignment.Center;return text;}
  void AddMenu(ContextMenu menu,string key,Action action){var item=new MenuItem{Header=L.T(key)};item.Click+=(o,e)=>U.Safe(this,action);menu.Items.Add(item);}
  void History(StackPanel host,List<Session> sessions){host.Children.Add(U.Text(L.T("history"),22,"#1D1D1F",true));if(sessions.Count==0)host.Children.Add(U.Card(U.Text(L.T("nohistory"),17,"#86868B")));
   foreach(var s in sessions.OrderByDescending(s=>s.startTime)){
    var grid=new Grid{Margin=new Thickness(0,4,0,0)};grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var left=new StackPanel{Margin=new Thickness(0,0,14,0)};left.Children.Add(U.Text(s.gameName,17,"#1D1D1F",true));left.Children.Add(U.Text(L.Date(s.startTime)+(s.endTime==null?"":"  →  "+L.Date(s.endTime)),12,"#86868B"));grid.Children.Add(left);var right=new StackPanel{VerticalAlignment=VerticalAlignment.Center};right.Children.Add(U.Text(L.Duration(s.durationSeconds),18,"#1D1D1F",true));right.Children.Add(U.Text(L.T(s.status),12,s.status=="completed"||s.status=="running"?"#28824B":"#86868B"));Grid.SetColumn(right,1);grid.Children.Add(right);
    if(s.status!="running"){var del=U.Button("×",()=>{if(MessageBox.Show(this,L.T("deleteConfirm"),L.T("title"),MessageBoxButton.OKCancel)==MessageBoxResult.OK){app.Store.Delete(s);Render();}});del.ToolTip=L.T("delete");del.Margin=new Thickness(12,0,0,0);Grid.SetColumn(del,2);grid.Children.Add(del);}host.Children.Add(U.Card(grid,new Thickness(22)));}
  }
  void Settings(StackPanel host){
   var general=new StackPanel();general.Children.Add(U.Text(L.T("language"),18,"#1D1D1F",true));string[] codes={"system","zh-CN","zh-TW","en","ja"};var lang=new ComboBox{ItemsSource=new[]{L.T("system"),"简体中文","繁體中文","English","日本語"},SelectedIndex=Math.Max(0,Array.IndexOf(codes,app.Store.Config.language)),Margin=new Thickness(0,12,0,0),Padding=new Thickness(10),MaxWidth=310,HorizontalAlignment=HorizontalAlignment.Left,MinWidth=250};lang.SelectionChanged+=(o,e)=>{app.Store.Config.language=codes[lang.SelectedIndex];app.Store.SaveConfig();L.Set(app.Store.Config.language);app.RefreshTray();Render();};general.Children.Add(lang);host.Children.Add(U.Card(general));
   var behavior=new StackPanel();behavior.Children.Add(U.Text(L.T("behavior"),18,"#1D1D1F",true));var auto=new CheckBox{Content=L.T("autostart"),IsChecked=App.Autostart,Margin=new Thickness(0,17,0,12)};auto.Click+=(o,e)=>U.Safe(this,()=>App.SetAutostart(auto.IsChecked==true));behavior.Children.Add(auto);behavior.Children.Add(U.Text(L.T("trayInfo"),13,"#86868B"));behavior.Children.Add(U.Button(L.T(app.Tracker.Paused?"resume":"pause"),()=>{app.Tracker.SetPaused(!app.Tracker.Paused);app.RefreshTray();Render();}));host.Children.Add(U.Card(behavior));
   var data=new StackPanel();data.Children.Add(U.Text(L.T("data"),18,"#1D1D1F",true));var buttons=new WrapPanel{Margin=new Thickness(0,13,0,0)};buttons.Children.Add(U.Button(L.T("backup"),()=>U.Safe(this,()=>{var dialog=new Microsoft.Win32.SaveFileDialog{Filter="JSON|*.json",FileName="playtime-backup-"+DateTime.Now.ToString("yyyyMMdd")+".json"};if(dialog.ShowDialog(this)==true){app.Store.Export(dialog.FileName);MessageBox.Show(this,L.T("exported"),L.T("title"));}})));buttons.Children.Add(U.Button(L.T("restore"),()=>U.Safe(this,()=>{var d=new Microsoft.Win32.OpenFileDialog{Filter="JSON|*.json"};if(d.ShowDialog(this)==true){app.Store.Import(d.FileName);app.Tracker.Changed();MessageBox.Show(this,L.T("imported"),L.T("title"));Render();}})));buttons.Children.Add(U.Button(L.T("legacy"),()=>U.Safe(this,()=>{using(var d=new Forms.FolderBrowserDialog{Description=L.T("importFirst")})if(d.ShowDialog()==Forms.DialogResult.OK){app.Store.ImportLegacy(d.SelectedPath);app.Tracker.Changed();MessageBox.Show(this,L.T("imported"),L.T("title"));Render();}})));buttons.Children.Add(U.Button(L.T("datafolder"),()=>Process.Start("explorer.exe",app.Store.Root)));data.Children.Add(buttons);host.Children.Add(U.Card(data));
  }
  void Welcome(){var w=U.Dialog(this,L.T("title"));var panel=new StackPanel{Margin=new Thickness(28)};panel.Children.Add(U.Text(L.T("welcome"),22,"#1D1D1F",true));panel.Children.Add(new Border{Height=16});panel.Children.Add(U.Text(L.T("welcomeBody"),14,"#6E6E73"));var auto=new CheckBox{Content=L.T("autostart"),IsChecked=false,Margin=new Thickness(0,22,0,22)};panel.Children.Add(auto);panel.Children.Add(U.Button(L.T("continue"),()=>U.Safe(w,()=>{if(auto.IsChecked==true)App.SetAutostart(true);app.Store.Config.onboardingComplete=true;app.Store.SaveConfig();w.Close();}),true));w.Content=panel;w.ShowDialog();}
  public void EditGame(Game existing,string file){U.Safe(this,()=>{
   Game draft=existing==null?new Game():new Game{id=existing.id,name=existing.name,executable=existing.executable,arguments=existing.arguments,workingDirectory=existing.workingDirectory,originalShortcut=existing.originalShortcut,trackingDirectory=existing.trackingDirectory,processNames=existing.processNames,enabled=existing.enabled};
   if(file!=null)FillFromFile(draft,file);
   var w=U.Dialog(this,L.T(existing==null?"add":"edit"),660);var panel=new StackPanel{Margin=new Thickness(26)};var name=U.Field(panel,"name",draft.name);var target=U.Field(panel,"file",draft.executable);var advanced=new StackPanel();var args=U.Field(advanced,"args",draft.arguments);var work=U.Field(advanced,"workdir",draft.workingDirectory);var proc=U.Field(advanced,"process",string.Join(", ",draft.processNames));var dir=U.Field(advanced,"directory",draft.trackingDirectory);
   Action fill=()=>{name.Text=draft.name??"";target.Text=draft.executable??"";args.Text=draft.arguments??"";work.Text=draft.workingDirectory??"";proc.Text=string.Join(", ",draft.processNames);dir.Text=draft.trackingDirectory??"";};
   var tools=new WrapPanel();tools.Children.Add(U.Button(L.T("desktopShortcut"),()=>U.Safe(w,()=>{string selected=PickDesktopShortcut(w);if(selected!=null){FillFromFile(draft,selected);fill();}})));tools.Children.Add(U.Button(L.T("browse"),()=>U.Safe(w,()=>{var picker=new Microsoft.Win32.OpenFileDialog{Filter="EXE / LNK|*.exe;*.lnk|EXE|*.exe|LNK|*.lnk|All files|*.*"};if(picker.ShowDialog(w)==true){FillFromFile(draft,picker.FileName);fill();}})));tools.Children.Add(U.Button(L.T("chooseRunning"),()=>{Observed p=PickProcess(w);if(p!=null){if(string.IsNullOrWhiteSpace(name.Text))name.Text=p.Name;if(string.IsNullOrWhiteSpace(target.Text))target.Text=p.Path;proc.Text=p.Name;dir.Text=Path.GetDirectoryName(p.Path);if(string.IsNullOrWhiteSpace(work.Text))work.Text=dir.Text;}}));panel.Children.Add(tools);
   panel.Children.Add(new Expander{Header=L.T("advanced"),Content=advanced,Margin=new Thickness(0,16,0,16)});var enabled=new CheckBox{Content=L.T("enabled"),IsChecked=draft.enabled,Margin=new Thickness(0,0,0,18)};panel.Children.Add(enabled);
   panel.Children.Add(U.Row(U.Button(L.T("save"),()=>U.Safe(w,()=>{
    draft.name=name.Text.Trim();draft.executable=target.Text.Trim();draft.arguments=args.Text;draft.workingDirectory=work.Text.Trim();draft.processNames=proc.Text.Split(new[]{',','，',';'},StringSplitOptions.RemoveEmptyEntries).Select(n=>Path.GetFileNameWithoutExtension(n.Trim())).ToArray();draft.trackingDirectory=dir.Text.Trim();draft.enabled=enabled.IsChecked==true;
    if(draft.processNames.Length==0&&File.Exists(draft.executable))draft.processNames=new[]{Path.GetFileNameWithoutExtension(draft.executable)};if(string.IsNullOrWhiteSpace(draft.trackingDirectory)&&File.Exists(draft.executable))draft.trackingDirectory=Path.GetDirectoryName(draft.executable);if(string.IsNullOrWhiteSpace(draft.workingDirectory))draft.workingDirectory=Path.GetDirectoryName(draft.executable);
    if(!File.Exists(draft.executable)){MessageBox.Show(w,L.T("invalid"),L.T("title"));return;}try{Store.ValidateGame(draft);}catch{MessageBox.Show(w,L.T("invalid"),L.T("title"));return;}
    lock(app.Store.Gate){if(app.Store.Config.games.Any(g=>g.id!=draft.id&&string.Equals(g.executable,draft.executable,StringComparison.OrdinalIgnoreCase))){MessageBox.Show(w,L.T("duplicate"),L.T("title"));return;}int index=app.Store.Config.games.FindIndex(g=>g.id==draft.id);if(index<0)app.Store.Config.games.Add(draft);else app.Store.Config.games[index]=draft;app.Store.SaveConfig();}app.Tracker.Changed();w.Close();Render();
   }),true),U.Button(L.T("cancel"),()=>w.Close())));var actions=(UIElement)panel.Children[panel.Children.Count-1];panel.Children.Remove(actions);((FrameworkElement)actions).Margin=new Thickness(26,10,26,20);var layout=new DockPanel();DockPanel.SetDock(actions,Dock.Bottom);layout.Children.Add(actions);layout.Children.Add(new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});w.Content=layout;w.AllowDrop=true;w.Drop+=(o,e)=>{if(e.Data.GetDataPresent(DataFormats.FileDrop))U.Safe(w,()=>{FillFromFile(draft,((string[])e.Data.GetData(DataFormats.FileDrop))[0]);fill();});};w.ShowDialog();
  });}
  public static void FillFromFile(Game draft,string file){string target=file,args="",work=Path.GetDirectoryName(file);if(string.Equals(Path.GetExtension(file),".lnk",StringComparison.OrdinalIgnoreCase)){dynamic shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic link=shell.CreateShortcut(file);try{target=(string)link.TargetPath;args=(string)link.Arguments;work=(string)link.WorkingDirectory;draft.originalShortcut=file;}finally{Marshal.FinalReleaseComObject(link);Marshal.FinalReleaseComObject(shell);}}
   if(!File.Exists(target)||!string.Equals(Path.GetExtension(target),".exe",StringComparison.OrdinalIgnoreCase))throw new InvalidDataException(L.T("invalid"));draft.executable=Path.GetFullPath(target);draft.arguments=args;draft.workingDirectory=string.IsNullOrWhiteSpace(work)?Path.GetDirectoryName(target):work;draft.trackingDirectory=Path.GetDirectoryName(target);draft.processNames=new[]{Path.GetFileNameWithoutExtension(target)};string description=FileVersionInfo.GetVersionInfo(target).FileDescription;draft.name=string.IsNullOrWhiteSpace(description)?Path.GetFileNameWithoutExtension(target):description;
  }
  public static List<DesktopLink> DesktopShortcuts(params string[] directories){var result=new List<DesktopLink>();var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(string directory in directories.Where(d=>!string.IsNullOrWhiteSpace(d)&&Directory.Exists(d))){foreach(string file in Directory.GetFiles(directory,"*.lnk",SearchOption.TopDirectoryOnly)){if(seen.Add(file))result.Add(new DesktopLink{Path=file,Label=Path.GetFileNameWithoutExtension(file)});}}return result.OrderBy(x=>x.Label,StringComparer.CurrentCultureIgnoreCase).ToList();}
  string PickDesktopShortcut(Window owner){string selected=null;var links=DesktopShortcuts(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),Environment.GetFolderPath(Environment.SpecialFolder.CommonDesktopDirectory));var w=U.Dialog(owner,L.T("desktopShortcut"),620);w.Height=520;w.SizeToContent=SizeToContent.Manual;var panel=new DockPanel{Margin=new Thickness(22)};var top=new StackPanel();top.Children.Add(U.Text(L.T("desktopPickInfo"),13,"#6E6E73"));var search=new TextBox{Margin=new Thickness(0,12,0,12),Padding=new Thickness(8)};top.Children.Add(search);DockPanel.SetDock(top,Dock.Top);panel.Children.Add(top);var list=new ListBox{DisplayMemberPath="Label",HorizontalContentAlignment=HorizontalAlignment.Stretch};Action filter=()=>list.ItemsSource=links.Where(x=>x.Label.IndexOf(search.Text,StringComparison.CurrentCultureIgnoreCase)>=0).ToList();search.TextChanged+=(o,e)=>filter();var bottom=U.Row(U.Button(L.T("save"),()=>{var item=list.SelectedItem as DesktopLink;if(item!=null){selected=item.Path;w.Close();}},true),U.Button(L.T("cancel"),()=>w.Close()));DockPanel.SetDock(bottom,Dock.Bottom);panel.Children.Add(bottom);panel.Children.Add(list);filter();w.Content=panel;w.ShowDialog();return selected;}
  Observed PickProcess(Window owner){Observed selected=null;var w=U.Dialog(owner,L.T("chooseRunning"),760);w.Height=550;w.SizeToContent=SizeToContent.Manual;var panel=new DockPanel{Margin=new Thickness(22)};var top=new StackPanel();top.Children.Add(U.Text(L.T("startPick"),13,"#86868B"));var search=new TextBox{Margin=new Thickness(0,10,0,12),Padding=new Thickness(8)};top.Children.Add(search);DockPanel.SetDock(top,Dock.Top);panel.Children.Add(top);var list=new ListBox{DisplayMemberPath="Display",HorizontalContentAlignment=HorizontalAlignment.Stretch};List<Observed> values=null;Action refresh=()=>{values=Tracker.ScanVisibleWindows();list.ItemsSource=values.Where(p=>p.Display.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0).ToList();};var bottom=U.Row(U.Button(L.T("refresh"),refresh),U.Button(L.T("save"),()=>{selected=list.SelectedItem as Observed;if(selected!=null)w.Close();},true));DockPanel.SetDock(bottom,Dock.Bottom);panel.Children.Add(bottom);panel.Children.Add(list);search.TextChanged+=(o,e)=>{if(values!=null)list.ItemsSource=values.Where(p=>p.Display.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0).ToList();};refresh();w.Content=panel;w.ShowDialog();return selected;}
  void Launch(Game g){U.Safe(this,()=>{if(!File.Exists(g.executable))throw new FileNotFoundException(L.T("notFound"));using(var p=Process.Start(new ProcessStartInfo(g.executable,g.arguments??""){WorkingDirectory=g.workingDirectory,UseShellExecute=true})){};app.Tracker.Changed();});}
  void Manual(Game g){var w=U.Dialog(this,L.T("manual"),460);var panel=new StackPanel{Margin=new Thickness(24)};var input=U.Field(panel,"manualHint","");panel.Children.Add(U.Text(L.T("manualNote"),12,"#86868B"));panel.Children.Add(U.Button(L.T("save"),()=>{double minutes;if(!double.TryParse(input.Text,out minutes)||double.IsNaN(minutes)||double.IsInfinity(minutes)||minutes<=0||minutes>52560000)return;var now=DateTimeOffset.Now;app.Store.Finish(new Session{gameId=g.id,gameName=g.name,status="manual",runKey="manual-"+Guid.NewGuid().ToString("N"),startTime=now.ToString("o"),endTime=now.ToString("o"),lastHeartbeat=now.ToString("o"),durationSeconds=minutes*60});w.Close();Render();},true));w.Content=panel;w.ShowDialog();}
  void Help(){var w=U.Dialog(this,L.T("help"),640);var panel=new StackPanel{Margin=new Thickness(26)};panel.Children.Add(U.Text(L.T("title"),24,"#1D1D1F",true));string path=Path.Combine(App.Base,"docs","help."+L.Language+".txt");panel.Children.Add(new TextBlock{Text=File.Exists(path)?File.ReadAllText(path):L.T("welcomeBody"),TextWrapping=TextWrapping.Wrap,LineHeight=24,Margin=new Thickness(0,18,0,0)});w.Content=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};w.ShowDialog();}
 }
}
